### ISSUE TITLE
Oberai Hacks 

### ISSUE THREAD

**Issue by vedantbahel** [adityaoberai/hackathon-submissions-platform-template#4]
### Name

V Bahel

### Email Address

vbahel@oberaihacks.com

### Project Description

# Oberai Hacks 
This project aims at hacking Aditya Oberai's success mantra. 

### Inspiration behind the Project

Aditya Oberai is an inspiration. Be like Aditya.

### Tech Stack

Still thinking 

### Hackathon Track

Track 1

### Project Repo

qwerty

### Anything Else?

Great work!

### Rules and Code of Conduct

- [X] I agree to follow this hackathon's Rules and Code of Conduct

**Comment by adityaoberai** [comment]
Thanks a lot for the submission @vedantbahel 😆 
While I can't accept this submission here, I'm grateful for the thought 😁

**Comment by vedantbahel** [comment]
Ha ha.
No worries.🤣
